rmdir /s /q patch-data
xcopy /s /e /y atlas-scripts\data-section1\* patch-data\
Atlas.exe patch-data\0.BIN atlas-scripts\0.txt
Atlas.exe patch-data\3.BIN atlas-scripts\3.txt
Atlas.exe patch-data\6.BIN atlas-scripts\6.txt
Atlas.exe patch-data\7.BIN atlas-scripts\7.txt
Atlas.exe patch-data\13.BIN atlas-scripts\13.txt
Atlas.exe patch-data\14.BIN atlas-scripts\14.txt
Atlas.exe patch-data\15.BIN atlas-scripts\15.txt
Atlas.exe patch-data\16.BIN atlas-scripts\16.txt
Atlas.exe patch-data\17.BIN atlas-scripts\17.txt
Atlas.exe patch-data\18.BIN atlas-scripts\18.txt
Atlas.exe patch-data\19.BIN atlas-scripts\19.txt
Atlas.exe patch-data\20.BIN atlas-scripts\20.txt
Atlas.exe patch-data\21.BIN atlas-scripts\21.txt
Atlas.exe patch-data\22.BIN atlas-scripts\22.txt
Atlas.exe patch-data\23.BIN atlas-scripts\23.txt
Atlas.exe patch-data\24.BIN atlas-scripts\24.txt
Atlas.exe patch-data\25.BIN atlas-scripts\25.txt
Atlas.exe patch-data\26.BIN atlas-scripts\26.txt
Atlas.exe patch-data\27.BIN atlas-scripts\27.txt
Atlas.exe patch-data\28.BIN atlas-scripts\28.txt
Atlas.exe patch-data\29.BIN atlas-scripts\29.txt
Atlas.exe patch-data\30.BIN atlas-scripts\30.txt
Atlas.exe patch-data\31.BIN atlas-scripts\31.txt
Atlas.exe patch-data\32.BIN atlas-scripts\32.txt
Atlas.exe patch-data\33.BIN atlas-scripts\33.txt
Atlas.exe patch-data\34.BIN atlas-scripts\34.txt
Atlas.exe patch-data\35.BIN atlas-scripts\35.txt
Atlas.exe patch-data\36.BIN atlas-scripts\36.txt
Atlas.exe patch-data\37.BIN atlas-scripts\37.txt
Atlas.exe patch-data\38.BIN atlas-scripts\38.txt
Atlas.exe patch-data\39.BIN atlas-scripts\39.txt
Atlas.exe patch-data\40.BIN atlas-scripts\40.txt
Atlas.exe patch-data\41.BIN atlas-scripts\41.txt
Atlas.exe patch-data\42.BIN atlas-scripts\42.txt
Atlas.exe patch-data\43.BIN atlas-scripts\43.txt
Atlas.exe patch-data\44.BIN atlas-scripts\44.txt
Atlas.exe patch-data\45.BIN atlas-scripts\45.txt
Atlas.exe patch-data\46.BIN atlas-scripts\46.txt
Atlas.exe patch-data\47.BIN atlas-scripts\47.txt
Atlas.exe patch-data\48.BIN atlas-scripts\48.txt
Atlas.exe patch-data\49.BIN atlas-scripts\49.txt
Atlas.exe patch-data\50.BIN atlas-scripts\50.txt
Atlas.exe patch-data\51.BIN atlas-scripts\51.txt
Atlas.exe patch-data\52.BIN atlas-scripts\52.txt
Atlas.exe patch-data\53.BIN atlas-scripts\53.txt
Atlas.exe patch-data\54.BIN atlas-scripts\54.txt
Atlas.exe patch-data\55.BIN atlas-scripts\55.txt
Atlas.exe patch-data\56.BIN atlas-scripts\56.txt
Atlas.exe patch-data\57.BIN atlas-scripts\57.txt
Atlas.exe patch-data\58.BIN atlas-scripts\58.txt
Atlas.exe patch-data\59.BIN atlas-scripts\59.txt
Atlas.exe patch-data\60.BIN atlas-scripts\60.txt
Atlas.exe patch-data\61.BIN atlas-scripts\61.txt
Atlas.exe patch-data\62.BIN atlas-scripts\62.txt
Atlas.exe patch-data\63.BIN atlas-scripts\63.txt
Atlas.exe patch-data\64.BIN atlas-scripts\64.txt
Atlas.exe patch-data\65.BIN atlas-scripts\65.txt
Atlas.exe patch-data\66.BIN atlas-scripts\66.txt
Atlas.exe patch-data\67.BIN atlas-scripts\67.txt
Atlas.exe patch-data\68.BIN atlas-scripts\68.txt
Atlas.exe patch-data\69.BIN atlas-scripts\69.txt
Atlas.exe patch-data\70.BIN atlas-scripts\70.txt
Atlas.exe patch-data\71.BIN atlas-scripts\71.txt
Atlas.exe patch-data\72.BIN atlas-scripts\72.txt
Atlas.exe patch-data\73.BIN atlas-scripts\73.txt
Atlas.exe patch-data\74.BIN atlas-scripts\74.txt
Atlas.exe patch-data\75.BIN atlas-scripts\75.txt
Atlas.exe patch-data\76.BIN atlas-scripts\76.txt
Atlas.exe patch-data\77.BIN atlas-scripts\77.txt
Atlas.exe patch-data\78.BIN atlas-scripts\78.txt
Atlas.exe patch-data\79.BIN atlas-scripts\79.txt
Atlas.exe patch-data\80.BIN atlas-scripts\80.txt
Atlas.exe patch-data\81.BIN atlas-scripts\81.txt
Atlas.exe patch-data\82.BIN atlas-scripts\82.txt
Atlas.exe patch-data\83.BIN atlas-scripts\83.txt
Atlas.exe patch-data\84.BIN atlas-scripts\84.txt
Atlas.exe patch-data\85.BIN atlas-scripts\85.txt
Atlas.exe patch-data\86.BIN atlas-scripts\86.txt
Atlas.exe patch-data\87.BIN atlas-scripts\87.txt
pause
